In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [2]:
new_york_tweets = pd.read_json("new_york.json", lines = True)
print(len(new_york_tweets))
print(new_york_tweets.columns)
print(new_york_tweets.loc[12]["text"])

4723
Index(['created_at', 'id', 'id_str', 'text', 'display_text_range', 'source',
       'truncated', 'in_reply_to_status_id', 'in_reply_to_status_id_str',
       'in_reply_to_user_id', 'in_reply_to_user_id_str',
       'in_reply_to_screen_name', 'user', 'geo', 'coordinates', 'place',
       'contributors', 'is_quote_status', 'quote_count', 'reply_count',
       'retweet_count', 'favorite_count', 'entities', 'favorited', 'retweeted',
       'filter_level', 'lang', 'timestamp_ms', 'extended_tweet',
       'possibly_sensitive', 'quoted_status_id', 'quoted_status_id_str',
       'quoted_status', 'quoted_status_permalink', 'extended_entities',
       'withheld_in_countries'],
      dtype='object')
Be best #ThursdayThoughts


In [3]:
london_tweets = pd.read_json('london.json', lines = True)
print(len(london_tweets))
#print(london_tweets.columns)
#print(london_tweets.loc[12]['text'])

5341


In [4]:
paris_tweets = pd.read_json('paris.json', lines = True)
print(len(paris_tweets))
#print(paris_tweets.columns)
#print(paris_tweets.loc[12]['text'])

2510


In [5]:
ny_text = new_york_tweets['text'].tolist()
paris_text = paris_tweets['text'].tolist()
london_text = london_tweets['text'].tolist()
#print(ny_text)

In [6]:
all_text = ny_text + paris_text + london_text
labels = [0] * len(ny_text) + [1] * len(paris_text) + [2] * len(london_text)

In [7]:
train_data, test_data, train_labels, test_labels = train_test_split(all_text, labels, test_size = 0.2, random_state = 1)
#print(len(train_data))
#print(len(test_data))

In [8]:
counter = CountVectorizer()
counter.fit(train_data)
train_counts = counter.transform(train_data)
test_counts = counter.transform(test_data)

In [9]:
#print(train_data[3])
#print(train_counts[3])

In [10]:
classifier = MultinomialNB()
classifier.fit(train_counts, train_labels)
predictions = classifier.predict(test_counts)

In [11]:
print(accuracy_score(test_labels, predictions))

0.6882703777335984


In [12]:
print(confusion_matrix(test_labels, predictions))

[[558  26 389]
 [ 36 363 102]
 [203  28 810]]
